### ISSUE TITLE
Tela de Login Simples com HTML e CSS

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#1]
//Código de uma página de Login com HTML e CSS

![captura de tela de 2018-02-19 18 11 32](https://user-images.githubusercontent.com/30798950/36397689-837d12c8-15a2-11e8-97e1-9cb8f3d1490a.png)

# HTML
```html
<!DOCTYPE html>
<html>
<head>
	<title>Mais um login</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="title"><h1>Cadastre se</h1></div>
	<div class="container">
		<div class="left"></div>
		<div class="right">
			<div class="formBox">
				<form>
					<p>Username</p>
					<input type="text" name="" placeholder="Online">
					<p>Password</p>
					<input type="password" name="" placeholder="......">
					<input type="submit" name="" value="Sign in">
					<a href="#">Forget your password?</a>
				</form>
			</div>
		</div>
	</div>
</body>
</html>
```

# CSS
```css
body
{
	margin: 0;
	padding: 0;
	background: #008B8B;
	background-size: cover;
	font-family: sans-serif;
}
.title
{
	text-align: center;
	padding: 50px 0 20px;
}
.title h1
{
	margin: 0;
	padding: 0;
	color: #fff;
	text-transform: uppercase;
	font-size: 36px;
}
.container
{
	width: 50%;
	height:400px;
	background: #fff;
	margin: 0 auto;
	border: 2px solid #fff;
	box-shadow: 0 15px 40px rgba(0,0,0,.5);
}
.container .left
{
	float: left;
	width: 50%;
	height: 400px;
	background: #483D8B;
}
.container .right
{
	float: right;
	width: 50%;
	height: 400px;
}
.formBox
{
	width: 100%;
	padding: 80px 40px;
	box-sizing: border-box;
	height: 400px;
	background: #fff;
}
.formBox p
{
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #483D8B;
}
.formBox input
{
	width: 100%;
	margin-bottom: 20px;
}
.formBox input[type="text"],
.formBox input[type="password"]
{
	border: none;
	border-bottom: 2px solid #483D8B;
	outline: none;
	height: 40px;
}
.formBox input[type="text"]:focus,
.formBox input[type="password"]:focus
{
	border-bottom: 2px solid #008B8B;
}
.formBox input[type="submit"]
{
	border: none;
	outline: none;
	height: 40px;
	color: #fff;
	background: #483D8B;
	cursor: pointer;
}
.formBox input[type="submit"]:hover
{
	background: #008B8B;
}
.formBox a
{
	color: #483D8B;
	font-size: 12px;
	font-weight: bold;
	text-decoration: none;
	width: 100%;
	text-align: center;
}
```
