### ISSUE TITLE
Página de Contatos com Inputs Animados

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#2]
//Código de uma página de Contato com HTML e CSS com inputs animados

![teste](https://user-images.githubusercontent.com/30798950/36399274-e2bda4a8-15a9-11e8-919f-f8d1d914f58a.gif)

# HTML
```html
<!DOCTYPE html>
<html>
<head>
	<title>Contato</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="box">
		<h2>Entre em contato</h2>
		<form>
			<div>
				<input type="text" name="" required="">
				<label>Nome</label>
			</div>
			<div>	
				<input type="text" name="" required="">
				<label>Email</label>
			</div>
			<div>	
				<input type="text" name="" required="">
				<label>Assunto</label>
			</div>
			<div>
				<textarea required=""></textarea>
				<label>Mensagem</label>
			</div>
			<div>
				<input type="submit" name="" value="Enviar">
			</div>
		</form>

	</div>

</body>
</html>
```
# CSS
```css
body
{
	margin: 0;
	padding: 0;
	font-family: sans-serif;
	background: url(fundo);
	background-repeat: no-repeat;
	background-size: cover;
}
.box
{
	position: absolute;
	top:50%;
	left: 50%;
	transform: translate(-50%, -50%);
	width: 400px;
	height: 600px;
	background: #fff;
	padding: 40px;
	box-sizing: border-box;
	border: 1px solid rgba(0, 0, 0, .1);
	box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
}
.box h2
{
	margin: 0 0 40px;
	padding: 0;
	color: #FFA500;
	text-transform: uppercase;
	text-align: center;
}
.box input
{
	padding: 10px 0;
	margin-bottom: 30px;
}
.box textarea
{
	height: 120px;
	padding: 10px 0;
	margin-bottom: 20px;
}
.box input,
.box textarea
{
	width: 100%;
	box-sizing: border-box;
	box-shadow: none;
	outline: none;
	border: none;
	border-bottom: 2px solid #999;
}
.box input[type="submit"]
{

	border-bottom: none;
	cursor: pointer;
	background: #FFA500;
	color:#fff;
	font-weight: bold;
	text-transform: uppercase;
	margin-bottom: 0;
	position: relative;
	top: 50px;
}
.box form div
{
	position: relative;
}
.box form div label
{
	position: absolute;
	top: 10px;
	left: 0;
	color: #999;
	transition: .5s;
	pointer-events: none;
}
.box input:focus ~ label,
.box textarea:focus ~ label,
.box input:valid ~ label,
.box textarea:valid ~ label
{
	top: -14px;
	left: 0;
	color: #FFA500;
	font-size: 12px;
	font-weight: bold;
}
.box input:focus,
.box textarea:focus,
.box input:valid,
.box textarea:valid
{
	transition: .5s;
	border-bottom: 2px solid #FFA500;
}

```
