### ISSUE TITLE
Botões em CSS

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#3]
// Exemplo de Botões feito com CSS e JavaScript
![teste](https://user-images.githubusercontent.com/30798950/36403021-06c27cfe-15c1-11e8-8913-b9df72ddff4c.gif)

# HTML
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <ul>
        <li>
            <a onclick="pegaValor(this)" class="first" href="#"><</a>
            <a onclick="pegaValor(this)" class="ativo" href="#">1</a>
            <a onclick="pegaValor(this)" href="#">2</a>
            <a onclick="pegaValor(this)" href="#">3</a>
            <a onclick="pegaValor(this)" href="#">4</a>
            <a onclick="pegaValor(this)" href="#">5</a>   
            <a onclick="pegaValor(this)" class="last" href="#">></a>
        </li>
    </ul>
    <div class="texto">
        <input id="txt" type="text">
    </div>
</body>
</html>
```

# CSS
```css
body
{
    margin: 0;
    padding: 0;
    background: blueviolet;
    font-family: sans-serif;
}
ul
{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background: white;
    margin: 0;
    padding: 0;
    border-radius: 25px;
    box-shadow: 0 15px 20px rgba(0, 0, 0, .5), 0 0 0 4px rgba(0, 0, 0, .1);
}

ul li
{
    list-style: none;
    display: flex;
}
ul li a
{
    display: block;
    width: 40px;
    height: 40px;
    text-align: center;
    line-height: 40px;
    background: white;
    color: #262626;
    text-decoration: none;
    border-radius: 4px;
    margin: 5px;
    box-shadow: inset 0 5px 10px rgba(0, 0, 0, .1), 0 2px 5px rgba(0, 0, 0, .5);
}
.first
{
    border-radius: 20px 0 0 20px; 
    /*top-left top-right bottom-right bottom-left*/
}
.last
{
    border-radius: 0 20px 20px 0;
}
ul li a:hover,
.ativo
{
    background: blueviolet;
    color: white;
}
.texto
{
    position: absolute;
    left: 50%;
    top: 20%;
    transform: translate(-50%, 20%);

}
.texto input
{
    border-radius: 20px;
    border: none;
    padding: 7px;
    text-align: center;
    color: blueviolet;
}
```
# JS
```javascript
function pegaValor(id){
    document.getElementById("txt").value = id.innerHTML;
}
```
