### ISSUE TITLE
Drop Bar com HTML e CSS

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#4]
// Uma pagina com uma barra com sub menus

![teste](https://user-images.githubusercontent.com/30798950/36403284-cd2e9c6e-15c2-11e8-87fe-15211fc1263f.gif)
# HTML
```html
<!DOCTYPE html>
<html>
<head>
	<title>Drop Menu</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="menu">
		<nav>
			<h2>João Vitor de Oliveira</h2>
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">Sobre</a>
					<ul>
						<li><a href="#">Lista1</a></li>
						<li><a href="#">Lista2</a></li> 
						<li><a href="#">Lista3</a></li>
						<li><a href="#">Lista4</a></li>
					</ul>
				</li>	
				<li><a href="#">Serviços</a>
					<ul>
						<li><a href="#">Lista1</a></li>
						<li><a href="#">Lista2</a></li> 
						<li><a href="#">Lista3</a></li>
						<li><a href="#">Lista4</a></li>
					</ul>
				</li>	
				<li><a href="#">Portifolio</a></li>
				<li><a href="#">Páginas</a>
					<ul>
						<li><a href="#">Lista1</a></li>
						<li><a href="#">Lista2</a></li> 
						<li><a href="#">Lista3</a></li>
						<li><a href="#">Lista4</a></li>
					</ul>
				</li>	
				<li><a href="#">Contato</a></li>
			</ul>
		</nav>	
	</div>
</body>
</html>
```

# CSS
```css
body
{
	margin: 0;
	padding: 0;
	font-family: sans-serif;
	background: url(fundo);
	background-size: cover;
}

.menu
{
	position: absolute;
	width: 100%;
	background: rgba(255,255,255,.8);
	padding: 0 100px;
	box-sizing: border-box;
	border-bottom: 1px solid rgba(0,0,0,.2);
}
/*.menu img
{
	float: left;
	width: 84px;
}*/
nav
{
	position: relative;
	float: right;
}
nav h2
{
	position: relative;
	margin: 0;
	padding: 25px 0 0 0;
	float: left;
	right: 300px;
	color: #483D8B;
}
nav ul
{
	margin: 0;
	padding: 0;
	display: flex;
}
nav ul li
{
	list-style: none;
}
nav ul li a
{
	display: block;
	color: #483D8B;
	text-transform: uppercase;
	font-weight: bold;
	padding: 33px 20px;
	text-decoration: none;
}
nav ul li ul
{
	display: block;
	background: rgba(255,255,255,.5);
	min-width: 250px;
	position: absolute;
	margin-top: 1px;
	box-shadow: 0 2px 5px rgba(0,0,0,.5);
	opacity: 0;
	visibility: hidden;
	transition: .5s;
	transform: translateY(40px);
}
nav ul li:hover ul
{
	opacity: 1;
	visibility: visible;
	transform: translateY(0px);	
}

nav ul li ul li a
{
	padding: 10px;
}
nav ul li a:hover
{
	background:#483D8B;
	color:#fff; 
}
```
