### ISSUE TITLE
Barra de Navegação com Efeito em CSS

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#5]
![teste](https://user-images.githubusercontent.com/30798950/36403778-dbd9473e-15c5-11e8-9b12-4a33dc596cda.gif)

# HTML 
```html
<!DOCTYPE html>
<html>
<head>
	<title>Barra de Navegação</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
	
	<nav>
		<div class="brand">
			<h2 id="nome"></h2>
		</div>
		<ul>
			<li><a href="#">Inicial</a></li>
			<li><a href="#">Sobre</a></li>
			<li><a href="#">Serviços</a></li>
			<li><a href="#">Portifolio</a></li>
			<li><a href="#">Contato</a></li>
		</ul>
	</nav>
	<section class="sec1"></section>
	<section class="sec2">
		<h1 align="center">Cascading Style Sheets (CSS)</h1>

		<p>É um simples mecanismo para adicionar estilo (cores, fontes, espaçamento, etc.) a um documento web[1].

		Em vez de colocar a formatação dentro do documento, o CSS cria um link para uma página que contém os estilos. Quando quiser alterar a aparência do portal, basta modificar apenas um arquivo[2].</p>

		<p>Com a variação de atualizações dos navegadores, o suporte ao CSS pode variar. O Internet Explorer 6, p. ex., tem suporte total a CSS1, e praticamente nulo a CSS2. Navegadores mais modernos, como Google Chrome e Mozilla Firefox, tem suporte maior, inclusive até a CSS3, ainda em desenvolvimento.</p>

		<p>A interpretação dos navegadores pode ser avaliada com o teste Acid2, que se tornou uma forma base de revelar quão eficiente é o suporte de CSS, fazendo com que a nova versão em desenvolvimento do Firefox seja totalmente compatível a ele, assim como o Opera já é. O Doctype informado, ou a ausência dele, determina o quirks mode ou o strict mode, modificando o modo como o CSS é interpretado e a página desenhada.</p>
	</section>
	<script type="text/javascript">
		var mudarNome = prompt("Digite um nome: ");

		if (mudarNome != null) {
			document.getElementById("nome").innerHTML = mudarNome;
		}
		else{
			document.getElementById("nome").innerHTML = "João Vitor";
		}
	</script>
</body>
</html>
```

# CSS
```css
body/*Formatando a pagina toda*/
{
	margin: 0;
	padding: 0;
	font-family: sans-serif;
}
section.sec1 /*Formatando a foto de baixo*/
{
	width: 100%;
	height: 80vh;
	box-sizing: border-box;
	background: url(fundo);
	background-size: cover;
	border-bottom: 1px solid #262626;

}
section.sec2
{
	padding: 100px;
}
section.sec2 h2
{
	width: 100%;
	text-align: center;
}
nav /*Formatando as propriedades da barra*/
{
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 70px;
	background: rgba(0,0,0,.6);
	padding: 0 100px;
	box-sizing: border-box;
}
nav .brand /*Formatando a posição do h2*/
{
	float: left;
	height: 100%;
	line-height: 70px;
}
nav .brand h2 /*Formatando o h2*/
{
	margin: 0;
	padding: 0;
	color: #fff;
}
nav ul /*Formatando a posiçao da lista*/
{
	float: right;
	display: flex; /*Torna a lista horizontal*/
	margin: 0;
	padding: 0;
}
nav ul li
{
	list-style: none;
}
nav ul li a
{
	position: relative;
	display: block;
	height: 70px;
	line-height: 70px;
	padding: 0 20px; 
	box-sizing: border-box;
	color: #fff;
	text-decoration: none;
	text-transform: uppercase;
	transition: .5s;
}
nav ul li a:hover
{
	color: #262626;
}
nav ul li a:before
{
	content: '';
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background: #fff;
	z-index: -1;
	transform-origin: top;
	transform: scaleY(0);
	transition: transform .5s;
}
nav ul li a:hover:before
{
	transform-origin: bottom;
	transform: scaleY(1);
	transition: transform .5s;
}

```
