### ISSUE TITLE
Tela de Login Transparente CSS

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#6]
![captura de tela de 2018-02-19 22 51 00](https://user-images.githubusercontent.com/30798950/36404051-645ba1e6-15c7-11e8-8342-4e9d315060f4.png)

# HTML
```html
<!DOCTYPE html>
<html>
<head>
	<title>Tela bonita</title>
	<meta charset="utf-8"> <!-- Aceita letras e acentos portugues-->
	<link rel="stylesheet" type="text/css" href="first.css"> <!-- Conecta o arquivo css ao html-->
</head>
<body>
	<div class="caixaLogin"> <!-- Cria uma divisoria, "class" é o nome dado a essa divisoria quando formatar no css-->
		<img src="user.png" class="imagem"> <!-- Adciona uma imagem-->
		<h2>Faça o Login Aqui!</h2><!--Sub-titulo -->
		<form><!-- Cria campos de texto, senha, botões e outros-->
			<p>Email</p><!-- uma frase-->
			<input type="text" name="" placeholder="Entre com o Email"><!-- Campo para texto-->
			<p>Senha</p><!-- Frase-->
			<input type="password" name="" placeholder="••••••"><!-- Cria um campo para senha-->
			<input type="submit" name="" value="Entrar"><!--Cria um botão -->
			<a href="https://www.google.com">Esqueceu a Senha?</a><!--Cria uma frase com hyperlink -->
		</form>
	</div>
</body>
</html>
```

#CSS 
```css
body /*Modificando a aparencia do campo Body */
{
	margin: 0;
	padding: 0;
	background: url(fundo.jpeg);
	background-size: cover;
	font-family: sans-serif;
}
.caixaLogin /* Modificar a aparencia de quem tiver a caixaLogin como classe*/
{
	position: absolute;
	top: 50%; /* acrescenta espaço a cima equivalente a 50% da tela*/
	left: 50%; /*acrescenta espaço a esquerda equivalente a 50% da tela*/
	transform: translate(-50%,-50%);/* Deixou os lados iguais*/
	width: 350px;/*criando uma caixa no centro da tela*/
	height: 520px;/*criando uma caixa no centro da tela*/
	padding: 80px 40px;
	box-sizing: border-box;
	background: rgba(0,0,0,.8);/*criando uma caixa no centro da tela com pouca transparencia*/
}
.imagem
{
	width: 100px;/*largura da foto*/
	height:100px;/*altura da foto*/
	border-radius: 50%;
	overflow: hidden;
	position: absolute;
	top: calc(-100px/2);
	left: calc(50% - 50px);
}
h2
{
	margin: 0;
	padding: 0 0 20px;
	color: #efed40;
	text-align: center;
}
.caixaLogin p
{
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #fff;
}
.caixaLogin input
{
	width: 100%;
	margin-bottom: 20px;/*Cria uma margem(distancia)na parte de baixo*/
}
.caixaLogin input[type="text"], .caixaLogin input[type="password"]

{
	border: none;
	border-bottom: 1px solid #fff;/*Cria uma pequena borda abaixo*/
	background: transparent;
	outline: none;
	height: 40px;
	color: #fff;
	font-size: 16px;
}
::placeholder
{
	color: rgba(255,255,255,.5);
}
.caixaLogin input[type ="submit"]
{
	border: none;
	outline: none;
	height: 40px;
	color: #fff;
	font-size: 16px;
	border-radius: 20px;
	background: #66CDAA;
	cursor: pointer;
}
.caixaLogin input[type="submit"]:hover
{
	background: #fff;/*cor do fundo*/
	color: #262626;/*cor da letra*/
}
.caixaLogin a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration: none;
	position: absolute;
	bottom: 50px;
	right: 97px;

}
```
