### ISSUE TITLE
Tela de Login Transparente CSS 2

### ISSUE THREAD

**Issue by JoaoVitorDeOliveira** [JoaoVitorDeOliveira/Projetos-Front-End#7]
![teste](https://user-images.githubusercontent.com/30798950/36404255-6cc1d87c-15c8-11e8-9eba-e0dc475b7661.gif)

# HTML
``` html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
   <section>
       <div class="container">
           <div class="login-form">
               <h1>Sign In</h1>
               <form>
                   <input type="text" placeholder="User">
                   <input type="password" placeholder="Password">
                   <input type="submit" value="Login">
               </form>
               <a href="#">Forget Password</a>
           </div>
       </div>
   </section>
</body>

</html>
```

# CSS
```css
body
{
    margin: 0;
    padding: 0;
    font-family: sans-serif;
}
section
{
    width: 100%;
    height: 100vh;
    background: url(projetosHtml/bg.jpg);
    background-size: cover;
}
.container
{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 340px;
    text-align: center;
}
.login-form
{
   position: relative;
   box-sizing: border-box;
   padding: 60px 30px;
   transition: .5s;
   border-radius: 10%;
}
.login-form:hover
{
    background: rgba(5, 0, 0, 0.3);
    border-radius: 10%;
    box-shadow: 0 0 20px rgba(0, 0, 0, .2);
}
.login-form h1
{
    color: rgb(250, 250, 250);
    font-weight: bold;
    text-transform: uppercase;
    font-size: 30px;
    
}
.login-form input
{
    display: block;
    width: 100%;
    padding: 10px 20px;
    box-sizing: border-box;
    margin-bottom: 20px;
    border-radius: 25px;
    outline: none;
    font-size: 14px;
    letter-spacing: 1px;
    color: rgb(0, 0, 0);
    text-transform: uppercase;
    border: none;    
}

.login-form input[type = "submit"]:hover
{
    background-color: rgb(255, 10, 92);
    color: white;
    font-weight: bold;
    cursor: pointer;
    transition: .3s;
}
.login-form a
{
    color: white;
    text-decoration: none;
    text-transform: uppercase;
    font-weight: bold;
}
.login-form a:hover
{
    color: rgb(255, 10, 92);
    text-decoration: none;
    text-transform: uppercase;
    font-weight: bold;
    transition: .5s;
}
```
